### ISSUE TITLE
Modifier la première phrase 

### ISSUE THREAD

**Issue by ludovicplt** [ju-lit-hein/WatSnap#1]
Je recommande de modifier la première phrase  du sujet par "Aujourd'hui nous allons application qui permet de prendre des photos avec de philtres comme watsap" ou quelque chose du genre.

Et d'ailleur arrivez un peux avant l'heure pour bien avoir le temps d'installer les pc

**Comment by ju-lit-hein** [comment]
Nous vous remercions de ce tres pertinent avis, il a d'ores et deja ete pris en compte.
Cordialement, 
Julien et Leo.
